server:
  port: 8083
  error:
    include-message: always
local:
  property:
    host:
      ms-bank-account: ms-bank-account
      ms-client: ms-client
      ms-credits: ms-credit
      ms-loan: ms-loan
      ms-debit-card: ms-debit-card
      ms-mobile-wallet: ms-mobile-wallet
spring:
  application:
    name: service-movement
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/MovementsDB
      auto-index-creation: true
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topic:
      mobile:
        name: mobile-wallet-topic
      bank:
        name: bank-account-topic
eureka:
  client:
    service-url:
      defaultZone: http://ms-discovery:9093/eureka
resilience4j:
  circuitbreaker:
    instances:
      creditCB:
        failureRateThreshold: 50
        minimumNumberOfCalls: 4
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 8
        waitDurationInOpenState: 2s
        permittedNumberOfCallsInHalfOpenState: 3
      bankaccountCB:
        failureRateThreshold: 50
        minimumNumberOfCalls: 4
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 8
        waitDurationInOpenState: 2s
        permittedNumberOfCallsInHalfOpenState: 3
      mobilewalletCB:
        failureRateThreshold: 50
        minimumNumberOfCalls: 4
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 8
        waitDurationInOpenState: 2s
        permittedNumberOfCallsInHalfOpenState: 3
message:
  demo: leido desde git
